# Defaults https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1

Layour/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/system/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
  Max: 15

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*

RSpec/DescribeClass:
  Exclude:
    - spec/system/*

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

Style/MixinUsage:
  Exclude:
    - bin/**

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
