# Defaults https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/system/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

Style/Documentation:
  Enabled: false
