name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
    - name: Rubocop
      uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile rubocop-rspec:gemfile
        reporter: github-pr-review
        rubocop_flags: -c .rubocop.yml
        filter_mode: file
